# This also makes no sense anymore we dont need the Frontend and Nginx container anymore

services:
  vidlocker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MODE=queue
      - DATABASE_URL=postgresql://vidlocker:<your_secure_password>@db:5432/vidlocker
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/output:/app/output
    container_name: vidlocker-backend
    networks:
      - vidlocker-network

  vidlocker-frontend:
    build: ./frontend
    ports:
      - 3002
    depends_on:
      - vidlocker
    networks:
      - vidlocker-network
    container_name: vidlocker-frontend

  db:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=vidlocker
      - POSTGRES_PASSWORD=<your_secure_password>
      - POSTGRES_DB=vidlocker
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vidlocker"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vidlocker-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vidlocker
      - vidlocker-frontend
    networks:
      - vidlocker-network

volumes:
  db_data:

networks:
  vidlocker-network:
    driver: bridge
