name: Rust Build & Docker

on:
  push:
    branches:
      - "*" # Runs for all branches
  pull_request:
    branches:
      - "*" # Runs for all pull requests

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Rust project
        working-directory: ./backend
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./backend
        run: cargo test --verbose

  docker:
    runs-on: ubuntu-latest
    needs: build # Ensure the build job completes before running docker job
    if: github.ref == 'refs/heads/release' # Only run this job if the branch is 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t backend -f backend/Dockerfile .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push your-image-name
