name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: attackly/vidlocker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      #- name: Run tests
      #  run: cargo test --verbose

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      # Push Docker image to DockerHub
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}
